# SPDX-License-Identifier: GPL-2.0-only
# Settings for compiling chora camera architecture

# Localized KCONFIG settings
CONFIG_SPECTRA_ISP := y
CONFIG_SPECTRA_ICP := y
CONFIG_SPECTRA_CRE := y
CONFIG_SPECTRA_SENSOR := y
CONFIG_SPECTRA_SECURE_SCM_API := y
CONFIG_SPECTRA_GET_IOMMU_FAULT_IDS := y
CONFIG_INTERCONNECT_QCOM := y
CONFIG_SPECTRA_SECURE_CAMERA_25 := y

# Flags to pass into C preprocessor
ccflags-y += -DCONFIG_SPECTRA_ISP=1
ccflags-y += -DCONFIG_SPECTRA_ICP=1
ccflags-y += -DCONFIG_SPECTRA_CRE=1
ccflags-y += -DCONFIG_SPECTRA_SENSOR=1
ccflags-y += -DCONFIG_SPECTRA_SECURE_SCM_API=1
ccflags-y += -DCONFIG_SPECTRA_GET_IOMMU_FAULT_IDS=1
ccflags-y += -DCONFIG_INTERCONNECT_QCOM=1
ccflags-y += -DCONFIG_SPECTRA_SECURE_CAMERA_25=1
